### ISSUE TITLE
Angular 14 Ivy?

### ISSUE THREAD

**Issue by marct83** [wittlock/ngx-image-zoom#107]
Any plans to publish an Ivy distribution?

**Comment by wittlock** [comment]
I just pushed version 2.0.0 where I've updated the library's angular dependency to version 15. I believe this has made it a pure ivy distribution now. Test it out and let me know if it works as you hope!

**Comment by wittlock** [comment]
I believe this to be fixed so I'm closing this. Feel free to comment for a re-open if this is not the case.
