### ISSUE TITLE
New hover-freeze and toggle-freeze

### ISSUE THREAD

**Issue by felipealbuquerq** [wittlock/ngx-image-zoom#118]
I need implements 'toggle-freeze' as was 'hover-freeze' and does 'hover-freeze' without needing to click to zoom: Whenever the mouse cursor moves over the thumbnail it will show the zoomed image, first click freezes the zoomed image where it is, second click unfreeze thumbnail.

[See this axample](https://ngx-image-zoom.web.app/)

**Comment by wittlock** [comment]
Thank you for your contribution. I just pushed 2.0.0 to npm with your changes and Angular 15 as my base (more ivy compatibility I hope). Decided to go a bit further with the version to make it super clear about the breaking change.
