### ISSUE TITLE
Feature request: Allow SafeUrl as image source

### ISSUE THREAD

**Issue by r0754497** [wittlock/ngx-image-zoom#129]
Currently the fullImage and thumbImage attributes only allow strings. SafeUrl works perfectly fine but just isn't allowed due to typing.
My situation requires a header to be added to the request and a blob to be piped through the sanitizer, the string requirement forces me to either put up an unsafe endpoint or store base64 strings in memory. Neither of which is acceptable for my usecase.
Made a pull request for it here: https://github.com/wittlock/ngx-image-zoom/pull/128/commits/b9fde0f931bc71e5d73be7ebd67f68073ef46c10

**Comment by wittlock** [comment]
Just pushed a 2.1.0 to npm with your pull request in it. Thank you for your contribution, I hope it works out for your needs!
