### ISSUE TITLE
Template parse error

### ISSUE THREAD

**Issue by sabeehshah** [wittlock/ngx-image-zoom#14]
```
<ngx-image-zoom
    [thumbImage]=https://i.imgur.com/jnRTmfe.jpg
    [fullImage]=https://i.imgur.com/z9yzdPO.jpg
>
</ngx-image-zoom>
```
![error](https://user-images.githubusercontent.com/26603601/44434173-b7e92000-a577-11e8-9a7e-ad629c15157e.PNG)

**Comment by Calicorio** [comment]
I'm having the same issue. Did you find a solution?
![image](https://user-images.githubusercontent.com/30621263/55481990-d80bb200-5623-11e9-958c-884639c2d753.png)

**Comment by tobmatth** [comment]
@Calicorio For the records: In case you use feature modules, be sure to also import `NgxImageZoomModule` in your feature module, e.g.

```
@NgModule({
  declarations: [...],
  imports: [
    ...,
    NgxImageZoomModule.forRoot()
  ],
  ...
})
export class AppModule { }

@NgModule({
  declarations: [...],
  imports: [
    ...,
    NgxImageZoomModule // <-- Add this line
  ],
  ...
})
export class YourFeatureModule { }

**Comment by RajeshBunny** [comment]
Even after changing its not working
