### ISSUE TITLE
Lens gets wrong location when it is used inside <ng-template>

### ISSUE THREAD

**Issue by MurhafSousli** [wittlock/ngx-image-zoom#17]
Hi I am trying to integrate your image zoom plugin in my gallery plugin. But the zoom lens gets wrong location, any idea?

Here is a [stackblitz](https://stackblitz.com/edit/ngx-gallery-fkwhez?file=src%2Fapp%2Fhome%2Fhome.component.html)

**Comment by wittlock** [comment]
I think this issue might be related to the one reported in #5, except a slightly different use case. Really appreciate the stackblitz as it gives me some more specific use cases I need to test for.

Life has been really crazy over the summer so I'm not sure when I'll get around to putting some more work into this project. Pull requests are welcome though, if you find a good solution.

**Comment by ashutiwari** [comment]
Has anyone able to find the solution ?

**Comment by wittlock** [comment]
Hi @MurhafSousli & @ashutiwari - I just released a beta version 0.6.0 to npm where I rewrote a big chunk of how I calculate the zooming position. This has resolved some issues I've seen with big pages and several ngx-image-zoom elements. Would you mind giving it a test and see if it resolves your issues as well?

**Comment by wittlock** [comment]
Closing this as fixed in 0.6.0, feel free to reopen or comment if there's still issues with some more details.
