### ISSUE TITLE
Template parse error: Can't bind to 'thumbImage' since it isn't a known property of 'ngx-image-zoom'.

### ISSUE THREAD

**Issue by Calicorio** [wittlock/ngx-image-zoom#31]
I've installed the package through npm, then import it in the ts module where I want to use it:
![image](https://user-images.githubusercontent.com/30621263/55488494-7bfb5a80-5630-11e9-85b4-256a5a3ca9d9.png)
And then in the html component I've used its tags:
![image](https://user-images.githubusercontent.com/30621263/55488604-a6e5ae80-5630-11e9-84cd-cd0d0369eee2.png)

When I do the npm start I get this error through the console where 'thumbImage' and 'fullImage' are not recognised as properties from ngx-image-zoom.
![image](https://user-images.githubusercontent.com/30621263/55488726-e14f4b80-5630-11e9-9b93-8956fc28d2ce.png)

Any ideas why could this be happening?

**Comment by wittlock** [comment]
Sorry about the late reply, maybe you've already solved this.

Maybe a silly question, and maybe it's just how you tried to show what you've done, but the @NgModule addition should be in your app.module.ts (where the @NgModule annotation should already exist) and not in your component.ts-file. Is that where you've put it?

**Comment by sashirajc** [comment]
For the benefit of future users.

I had the same problem. It was because I was using the package in a different module other than my main module. If you have multiple modules inside your app.module.ts, then you must import the package inside those modules instead of the app.module.ts

**Comment by akashutosh77** [comment]
thanks @sashirajc , my issue was same as that of yours

**Comment by wittlock** [comment]
Closing this as resolved question.
