### ISSUE TITLE
Lense position is calculated incorrectly inside modal popup dialog when vertical scroll is present on the viewport

### ISSUE THREAD

**Issue by dKab** [wittlock/ngx-image-zoom#32]
See this example: https://stackblitz.com/edit/angular-osmsac
if you click on first card image, modal will open where you can zoom the image and you can see that lense position is correct. However if you scroll down to card #15 or #20 and do the same, the lense will open at the bottom of the thumbnail this time and it's no longer following cursor - it's stuck in it's vertical position.

**Comment by dKab** [comment]
This happens because [event.pageY](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/pageY) property is used in `calculateZoomPosition` function:

    const top = (event.pageY - this.offsetTop + scrollTopOffset);

and `pageY` property  takes into account any vertical scrolling of the page.

So if you scroll document down and try to apply zoom inside modal it won't work because modal window is opened with position static applied to it effectively ignoring all the scroll that is present on the page. But lense doesn't know that and it calculates position to be far below the place of the thumbnail (`pageY` of the event is incorrect in this case)   as if there was no modal window opened. Therefore to fix this we need a to subtract the value of current scrollTop of the document from the `pageY` property of mouse event.

**Comment by wittlock** [comment]
Thank you for the bug report and a pull request to resolve it. I'll try to look at this in the near future and hopefully merge this fix into an upcoming release. Much appreciated and sorry for the delay getting around to it.

**Comment by wittlock** [comment]
Pull request #33 has been merged and released in module version 0.4.0, hopefully this fixes the issue, otherwise comment again and I'll reopen.
