### ISSUE TITLE
Issue in top and left values

### ISSUE THREAD

**Issue by hamzach96** [wittlock/ngx-image-zoom#34]
Hello, I am facing an issue with the zoom. Whenever I click on the image at a different position, it always zooms the image from the top. I checked through the HTML code, the top and left values for ngxZoomImageContainer remain zero. In short, the top and left are not changing.

Code:
<ngx-image-zoom 
	[zoomMode]="'click'" 
	[enableScrollZoom]="true"
	[maxZoomRatio]="5"
	[thumbImage]="img" 
	[fullImage]="img">
</ngx-image-zoom>

**Comment by wittlock** [comment]
I've encountered something similar to this while developing this plugin, but I can't remember exactly what caused it. Do you think it could be related to #32 ? In which case a fix is incoming soon. I'll try to experiment a little bit and see if I can remember how I encountered it.

**Comment by CarlosTorrecillas** [comment]
@wittlock any idea about when a new release of the package is coming out?

**Comment by wittlock** [comment]
@CarlosTorrecillas I don't want to promise anything since that just leads to disappointment when it cannot be met. But I'm doing my best to find the time to dig into some of these smaller issues so I can make a new release.

**Comment by wittlock** [comment]
Pull request #33 has been merged and is included in version 0.4.0 on npm, which is the fix for #32, hopefully this helps with your issue too. Please test and let me know if it alleviated your issue.

**Comment by wittlock** [comment]
No follow up so I'm going to close this as resolved. Feel free to report back if there's more information to be shared and it can be reopened.
