### ISSUE TITLE
ngx-image-zoom not working in component children

### ISSUE THREAD

**Issue by scavjr** [wittlock/ngx-image-zoom#40]
![Captura de Tela 2019-08-08 às 09 34 05](https://user-images.githubusercontent.com/48152617/62704061-ea766d80-b9c0-11e9-894c-fa492f15639f.jpg)
I made a web application using angular 8.
when I was using ngx-image-zoom 0.4.1, it didn't work on the children components.

**Comment by wittlock** [comment]
I don't think I've actually tried it with child components like this. In what way is it not working? Any errors? Incorrect behavior? Do you do anything different with the parameters to ngx-image-zoom?

A little more information would be helpful before I dig into this.

**Comment by scavjr** [comment]
When I click on it, nothing happens. No error. Sometimes clicking on it before the page loads complete displays a zoom snippet and then locks into that snippet. With the browser inspector open, I see that it doesn't have the style properties: "border-radius: display: top: left:"
Isn't "forChild" missing?
Or create a separate module for the component and declare it in that module?
![working](https://user-images.githubusercontent.com/48152617/62801522-55589f00-babc-11e9-91a4-78a39a05c951.jpg)
![child](https://user-images.githubusercontent.com/48152617/62801541-5b4e8000-babc-11e9-8cd6-cb5b4fad3070.jpg)

**Comment by wittlock** [comment]
Hi @scavjr - I just released a beta version 0.6.0 to npm where I rewrote a big chunk of how I calculate the zooming position. This has resolved some issues I've seen with big pages and several ngx-image-zoom elements. Would you mind giving it a test and see if it resolves your issues as well?

**Comment by wittlock** [comment]
Closing this as fixed in 0.6.0, feel free to reopen or comment if there's still issues with some more details.
