### ISSUE TITLE
Feature request: New zoom mode

### ISSUE THREAD

**Issue by noveltieng** [wittlock/ngx-image-zoom#42]
As per title, is it possible for the "click" zoom mode to return to original size during the second click.

Current behaviour:
1. Click on image, image zoom
2. Click on image again, nothing happens
3. Move out from image, goes back to original size

Desired behavior:
1. Click on image, image zoom
2. Click on image, goes back to original size

**Comment by wittlock** [comment]
Have you tried the 'toggle' zoom mode instead of 'click'? If 'toggle' is not what you are looking for could you try and explain the difference between 'toggle' and what you want?
