### ISSUE TITLE
compatibility with flexbox and transform

### ISSUE THREAD

**Issue by geekyposh** [wittlock/ngx-image-zoom#5]
I'm using this in conjunction with a carousel that uses flexbox and transform to display/animate the slides, and the zoom only works on the first slide. After a bit of digging I've found that newLeft needs to be set differently depending on the left value, so something like this:

`if(left > 0){
newLeft = Math.max(Math.min(left, this.thumbWidth), 0)
    }else{
            if(this.thumbWidth + left > 0){
                newLeft = Math.max(Math.min(this.thumbWidth + left, this.thumbWidth), 0);
            }else{
                newLeft = Math.max(Math.min(this.thumbWidth-(Math.abs(left)-this.thumbWidth), this.thumbWidth), 0);
            }
        }`

This is the example that worked in my case.

**Comment by wittlock** [comment]
Thanks for the report. Still looking for more use-cases to test the plugin in to figure out where things might break down. Unfortunately I'm down sick at the moment so it may take a little while before I can look into it, but I'll do it as soon as I get a chance.

**Comment by geekyposh** [comment]
I did a few more test cases on this, and found the better solution is to actually use getBoundingClientRect() instead of offsetLeft to calculate the left position, especially in cases where the image might initially be outside the viewport (ie. sliders).

**Comment by wittlock** [comment]
Hi @geekyposh - I just released a beta version 0.6.0 to npm where I rewrote a big chunk of how I calculate the zooming position, using getBoundingClientRect() as you suggested. This has resolved some issues I've seen with big pages and several ngx-image-zoom elements. Would you mind giving it a test and see if it resolves your issues as well?

**Comment by wittlock** [comment]
Closing this as fixed in 0.6.0, feel free to reopen or comment if there's still issues with some more details.
