### ISSUE TITLE
angular ivy support

### ISSUE THREAD

**Issue by rhutchison** [wittlock/ngx-image-zoom#50]
ERROR in node_modules/ngx-image-zoom/index.d.ts:4:23 - error NG6005: NgxImageZoomModule.forRoot returns a ModuleWithProviders type without a generic type argument. Please add a generic type argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, please contact the library authors.

4     static forRoot(): ModuleWithProviders;

**Comment by JulianH** [comment]
Hello @wittlock,
as Angular9 is now officially released, please consider to release a new version with support for Angular9. Thank you!
