### ISSUE TITLE
click on button outside image zoom in and zoom out

### ISSUE THREAD

**Issue by subrat7** [wittlock/ngx-image-zoom#52]
Hi 
Instead of scroll button inside the image to zoom in and zoom out 

I want to make two buttons 
1)Click on Zoom-in button( Zoom in the image)
2)Click on Zoom-out (Zoom out the image )

Please Guide me :)

**Comment by wittlock** [comment]
Hi there,
This isn't really a feature right now, but it's part of something I've been planning to add. Some controls to control the zooming with inputs instead. Both toggling the zooming on/off and also controlling what part of the image is zoomed on.
No timeline at the moment for such a feature though, but I want to add it.

**Comment by subrat7** [comment]
Thanks for the reply
hence closing this.
