### ISSUE TITLE
Pan image with toggle zoom

### ISSUE THREAD

**Issue by AaronLavers** [wittlock/ngx-image-zoom#53]
Is there a way to allow the panning of the image using the mouse when you're using the 'toggle' setting, like we have when using the 'click' setting?

My UI requires the toggle style of zooming, but then there doesn't appear to be a straightforward way to pan around the image other than zooming back out and toggling in on a different part of the image?

**Comment by wittlock** [comment]
Toggle is intended to not move the image around while zoomed. Does 'click' not do what you want? If so, what is the difference between what 'click' does and what you are looking for? I'd be happy to add more modes but right now I'm not sure I understand what you are looking for.

**Comment by AaronLavers** [comment]
I've noticed some peculiarities with the user experience when using 'click'. In toggle mode, the image returns to the default state when you unclick/click a second time. However with click mode, it doesn't seem to do that. 

The other main issue is that on mobiles, neither mode seems to allow for panning. Toggle would be preferable in this regard, as you would need to be able to touch the screen to pan as opposed to following mouse movements :)
