### ISSUE TITLE
when the version >9.0.0  the component is lose efficacy

### ISSUE THREAD

**Issue by doubleyangBaby** [wittlock/ngx-image-zoom#65]
This version of CLI is only compatible with Angular versions ^8.0.0-beta || >=8.0.0 <9.0.0,
but Angular version 9.0.0 was found instead.

When can I update it ？

**Comment by wittlock** [comment]
Super late here, but there's now a 1.0.0-beta.0 beta release out on npm. Hopefully a full release will come shortly too once I get some feedback the beta works. That should resolve this issue.
