### ISSUE TITLE
Can I use this for PDF is it possible my requirement is like that,suggest me how to dol

### ISSUE THREAD

**Issue by senthil123kumar** [wittlock/ngx-image-zoom#69]

**Comment by wittlock** [comment]
This library currently relies on the <img> tag to show the image and the zoom component. So without some browser plugin I doubt it would be able to show a pdf. I'm not sure if there is any way to natively show a pdf as part of a webpage. So if you want to use this library you would probably have to convert the pdfs to images in backend unless I'm unaware of some more recent development in browser capabilities.

**Comment by wittlock** [comment]
Closing this as out of scope for the project for now. I'd consider a pull request to add this feature but it seems like a big ask.
