### ISSUE TITLE
Zooming does not work when only thumb image url is provided

### ISSUE THREAD

**Issue by faraz-ahmad** [wittlock/ngx-image-zoom#74]
If fullImage image url not provided then zooming does not work. I have only one image URL to display. I don't have separate URL for full Image.

 <lib-ngx-image-zoom [thumbImage]=MY_IMAGE_URL  [magnification]="1"
                          [enableScrollZoom]="true">
  </lib-ngx-image-zoom>

**Comment by wittlock** [comment]
If you don't have a fullImage to provide but only a thumbImage then you must specify a magnification greater than 1 to get anything to happen. Thumbnail will be shown in its actual size and you can zoom in on it further. It's not great but it's an application I use myself and it's not half bad. Try setting magnification to "2".

**Comment by blitzmann** [comment]
Is there any way to have the thumb image shrink to it's container? I have a full size image coming from the server, and shrinking it down to a smaller space, and want to use image zoom to show the full res. But with this, I can only get it to show actual siize, which is much larger than the container for it.
