### ISSUE TITLE
Please make isReady publilc or export its value via @Output

### ISSUE THREAD

**Issue by siovene** [wittlock/ngx-image-zoom#80]
In my use-case, the full-size image might a very large file, so I first display a simple `img` pointing to the thumbnail, and then ngx-image-zoom would be ready, I'd replace the img with it.

But right now I cannot know when that's the case :(

**Comment by wittlock** [comment]
That should be easy enough to sort, I'll look into it!

**Comment by wittlock** [comment]
There's now a 1.0.0-beta.1 on npm as well that includes this change. Give it a spin. Since it's a beta release you have to specify version explicitly.
Should be a proper 1.0.0 out in a couple of days or so I think.

**Comment by siovene** [comment]
Thanks @wittlock, I will wait for 1.0.0 and then try it!
